---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        CF_API_TOKEN: "{{ .EXTERNAL_DNS_CLOUDFLARE_API_TOKEN }}"
        CF_ZONE_ID: "{{ .CLOUDFLARE_ZONE_ID }}"
  data:
    - secretKey: EXTERNAL_DNS_CLOUDFLARE_API_TOKEN
      remoteRef:
        key: db8c008b-20d9-4b8c-8d4f-d7e2c2114fe0
    - secretKey: CLOUDFLARE_ZONE_ID
      remoteRef:
        key: c95ec9d1-47d0-4b99-829f-dbb41ecf3dce
