---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-cloudflare
  values:
    fullnameOverride: external-dns-cloudflare
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: CF_API_TOKEN
      - name: CF_ZONE_ID
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: CF_ZONE_ID
    extraArgs:
      - --zone-id-filter=$(CF_ZONE_ID)
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --gateway-name=external
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters:
      - nasenov.dev
    serviceMonitor:
      enabled: true
