---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi
  storage:
    size: 16Gi
    storageClass: openebs-hostpath
  affinity:
    podAntiAffinityType: required

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: cnpg.nasenov.dev
                lbipam.cilium.io/ips: 192.168.0.44
            spec:
              type: LoadBalancer

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: preferred

  # bootstrap:
  #   initdb:
  #     import:
  #       type: monolith
  #       databases:
  #         - grafana
  #         - miniflux
  #         - miscale2pg
  #       roles:
  #         - grafana
  #         - miniflux
  #         - miscale2pg
  #         - _crunchypgbouncer
  #       source:
  #         externalCluster: crunchy-postgres

  # externalClusters:
  #   - name: crunchy-postgres
  #     connectionParameters:
  #       host: postgres-primary.database.svc.cluster.local
  #       dbname: postgres
  #       user: postgres
  #       sslmode: require
  #     password:
  #       name: postgres-pguser-postgres
  #       key: password

  bootstrap:
    recovery:
      source: origin

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage
          serverName: postgres

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage
