---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  affinity:
    podAntiAffinityType: required

  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8

  storage:
    size: 16Gi
    storageClass: openebs-hostpath

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: postgres.nasenov.dev
                lbipam.cilium.io/ips: 192.168.0.42
            spec:
              type: LoadBalancer

  enableSuperuserAccess: true

  superuserSecret:
    name: postgres-superuser

  primaryUpdateMethod: switchover

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: preferred

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage

  bootstrap:
    recovery:
      source: origin

  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage
          serverName: postgres
