---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana
spec:
  cluster:
    name: postgres
  name: grafana
  owner: grafana
  schemas:
    - name: grafana
      owner: grafana
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: miniflux
spec:
  cluster:
    name: postgres
  name: miniflux
  owner: miniflux
  schemas:
    - name: miniflux
      owner: miniflux
