---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        ACCESS_KEY: "{{ .POSTGRESQL_GARAGE_ACCESS_KEY }}"
        ACCESS_KEY_SECRET: "{{ .POSTGRESQL_GARAGE_ACCESS_KEY_SECRET }}"
  data:
    - secretKey: POSTGRESQL_GARAGE_ACCESS_KEY
      remoteRef:
        key: 28577773-0cde-47c9-90b2-0c136b2274c6
    - secretKey: POSTGRESQL_GARAGE_ACCESS_KEY_SECRET
      remoteRef:
        key: ad0bc000-ec94-4e08-a9bc-8df189f12b98
