---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres
  target:
    template:
      data:
        DATABASE_URL: "postgres://{{ .user }}:{{ .password }}@{{ .pgbouncer_host }}:{{ .pgbouncer_port }}/{{ .dbname }}"
        RUN_MIGRATIONS: "1"
  dataFrom:
    - extract:
        key: postgres-pguser-miniflux
      rewrite:
        - regexp:
            source: "-"
            target: "_"
