---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        CREATE_ADMIN: "1"
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASSWORD }}"
  data:
    - secretKey: MINIFLUX_ADMIN_USERNAME
      remoteRef:
        key: 29d524e4-42d1-4446-9dab-b48900ed5b32
    - secretKey: MINIFLUX_ADMIN_PASSWORD
      remoteRef:
        key: 1e1c7b52-4277-464d-bfbb-b48900ed43af
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres
  target:
    template:
      data:
        DATABASE_URL: "host=postgres-rw.database.svc.cluster.local port=5432 dbname={{ .username }} user={{ .username }} password={{ .password }}"
        RUN_MIGRATIONS: "1"
  dataFrom:
    - extract:
        key: postgres-miniflux
