---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: miniflux
  values:
    controllers:
      miniflux:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/miniflux/miniflux
              tag: 2.3.3@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
            env:
              PORT: &port 80
              METRICS_COLLECTOR: 1
              METRICS_ALLOWED_NETWORKS: 10.244.0.0/16
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
              - secretRef:
                  name: "{{ .Release.Name }}-database"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /liveness
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readiness
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        endpoints:
          - port: http

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nasenov.dev"
          - feeds.nasenov.dev
        parentRefs:
          - name: envoy-internal
            namespace: networking
