---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  values:
    controllers:
      qbittorrent:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.4@sha256:9307627e03981d5473aa31175ea76ed56ea3752333ca49d601b6af45e281e7ba
            env:
              TZ: Europe/Sofia
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
            probes:
              liveness:
                enabled: true
                port: *port
              readiness:
                enabled: true
                port: *port
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: *port
          bittorrent:
            port: *torrentPort

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nasenov.dev"
          - qb.nasenov.dev
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      bittorrent:
        kind: TCPRoute
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *torrentPort

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: truenas.nasenov.dev
        path: /mnt/tank/media
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
