---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu/api
      identityURL: https://vault.bitwarden.eu/identity
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: external-secrets-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: 02c405b4-b45f-465e-8b17-b43000f00874
      projectID: 8750bf6a-3102-4b1c-9caf-679556a08aa0
