apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:A8owepU5pFfRLh7dcsUhVGJoRLry6BL/EbozF4D7Mq0S69WQkkj9d7A5FOm5yRAmYeCOg9OiH0+tq9+aVpwk1IN5Q14pllcbv4UmQnchabz6WVKyYcNtQqZ7IsffRg==,iv:93R+2P/jwKtpzvEsF3GzbOR9lNLOXNHHsrsKNlb5+eg=,tag:pMxTPtL2MNR5au7BNEyQ/g==,type:str]
sops:
  age:
    - recipient: age128pzspekap6pjzu53vzfn9t6xpvazq0z6qxxj79v27mke4urup9qqqhq4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcW9vOEo5WkM0OXlubzRx
        emNLZ0FVOTJVZGpIUGxaK0QvNGVXTjk5ZEZVCnhJaHBUZXdPK2tmeWlIWWk3aFl5
        b0RUVlNyTU9IVGFKanVlTlplb0RnU00KLS0tIGo0aDErNEsrT2hZV01hSEhwc2dw
        eWpweXl4OC9YS1BrdWNobE9JOFlVbHcKu68BZgTFqZlr8PL5oZ5y3VYZtkS0lynJ
        d/AoPcnlKR8GDGmAnzD6dTG3RhUk6xe1RNOKSQPwz8r3uck103ZIXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T07:03:18Z"
  mac: ENC[AES256_GCM,data:biRtwPC38pAP8nBLDf2bUpN51OsfFLHAa9xoQGbAYWk05Ruusrs29dsL4J55TKr5I3VJfXc/q0li+nPsCk+V65fO7TfKnU2XG4V+wAWL/bVAdTzvRhN2ytiLgmUL2AxxGFObXZ9lpsKl0urzQJljgsX90p94eTM2qkieIO6GarM=,iv:YlIcHYunqFfzPGv8HZ2fi9mLClVV5DAxPF9AGUb6JFM=,tag:JoBJTJm2J1m49FFOn4zfTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
