---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: it-tools
  values:
    controllers:
      it-tools:
        strategy: RollingUpdate
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/it-tools
              tag: 2024.10.22@sha256:7f26ae8d7a4a58b8d70b685cba5cbaa54d7df876d9f8bae702207f45b06d9b7c
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nasenov.dev"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          it-tools:
            app:
              - path: /tmp
                subPath: tmp
