---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        config.js: |
          "use strict";

          module.exports = {
            action: "inject",
            apiKey: "{{ .CROSS_SEED_API_KEY }}",
            dataDirs: [
              "/data/downloads/manual",
              "/data/downloads/autobrr"
            ],
            delay: 30,
            flatLinking: false,
            fuzzySizeThreshold: 0.1,
            includeSingleEpisodes: false,
            linkCategory: "cross-seed",
            linkDirs: [
              "/data/downloads/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "partial",
            maxDataDepth: 3,
            outputDir: null,
            port: Number(process.env.CROSS_SEED_PORT),
            radarr: [
              "http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_KEY }}"
            ],
            seasonFromEpisodes: 1,
            skipRecheck: true,
            sonarr: [
              "http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_KEY }}"
            ],
            torrentClients: [
              "qbittorrent:http://{{ .QBITTORRENT_USERNAME }}:{{ .QBITTORRENT_PASSWORD }}@qbittorrent.default.svc.cluster.local"
            ],
            torznab: [
              "http://prowlarr.default.svc.cluster.local/4/api?apikey={{ .PROWLARR_KEY }}", // TL
              "http://prowlarr.default.svc.cluster.local/5/api?apikey={{ .PROWLARR_KEY }}", // HDT
              "http://prowlarr.default.svc.cluster.local/7/api?apikey={{ .PROWLARR_KEY }}" // ANT
            ],
            useClientTorrents: true
          };
  data:
    - secretKey: CROSS_SEED_API_KEY
      remoteRef:
        key: d109c0f8-0828-4d3e-bf53-b2860102377b
    - secretKey: RADARR_KEY
      remoteRef:
        key: d0491587-c8dc-4e81-a1f7-b27f01353cf5
    - secretKey: SONARR_KEY
      remoteRef:
        key: 2018ba36-f54b-4269-aa43-b27f01357eaa
    - secretKey: PROWLARR_KEY
      remoteRef:
        key: e6889f99-9261-41ae-b631-b27f01362650
    - secretKey: QBITTORRENT_USERNAME
      remoteRef:
        key: 57d6460b-b7cc-4269-9f45-b27f0136e722
    - secretKey: QBITTORRENT_PASSWORD
      remoteRef:
        key: cc69e0c0-3341-45f2-b0ae-b27f0136f9ea
