---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cross-seed
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cross-seed
  values:
    controllers:
      cross-seed:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.13.5@sha256:5582e38109145faf6203c844d61d2187368329bde7019a310d3922fef82d8fbf
            args: ["daemon"]
            env:
              TZ: Europe/Sofia
              CROSS_SEED_PORT: &port 80
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      secret-file:
        type: secret
        name: "{{ .Release.Name }}"
        globalMounts:
          - path: /config/config.js
            subPath: config.js
      media:
        type: nfs
        server: truenas.nasenov.dev
        path: /mnt/tank/media
        globalMounts:
          - path: /data/downloads
            subPath: downloads
      tmpfs:
        type: emptyDir
        advancedMounts:
          cross-seed:
            app:
              - path: /config/logs
                subPath: logs
