---
extends: default

ignore:
  - "*.sops.*"

rules:
  braces:
    max-spaces-inside: 1

  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  line-length: disable

  truthy:
    allowed-values: ["true", "false", "on"]
