---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/install
        value:
          crds: CreateReplace
          remediation:
            retries: -1
      - op: add
        path: /spec/upgrade
        value:
          cleanupOnFail: true
          crds: CreateReplace
          remediation:
            retries: 3
