---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns
spec:
  targetNamespace: kube-system
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  components:
    - ../../../../components/defaults
  path: ./kubernetes/apps/kube-system/coredns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
