---
version: v1alpha1
machine:
  sysctls:
    fs.inotify.max_queued_events: "65536"
    fs.inotify.max_user_watches: "524288"
    fs.inotify.max_user_instances: "8192"
    net.core.rmem_max: "7500000" # Cloudflared / QUIC
    net.core.wmem_max: "7500000" # Cloudflared / QUIC
  kernel:
    modules:
      - name: nbd
  kubelet:
    extraConfig:
      serializeImagePulls: false
  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
    - op: overwrite
      path: /etc/nfsmount.conf
      permissions: 0o644
      content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        nconnect=8
        noatime=True
        rsize=1048576
        wsize=1048576
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:admin
      allowedKubernetesNamespaces:
        - system-upgrade
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  apiServer:
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
    extraArgs:
      anonymous-auth: "true" # https://github.com/siderolabs/talos/issues/11324
    disablePodSecurityPolicy: true
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        memory: 2Gi
  coreDNS:
    disabled: true
  allowSchedulingOnControlPlanes: true
---
cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        "$patch": delete
