---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: openebs
volumeType: disk
provisioning:
  diskSelector:
    match: disk.model == "Samsung SSD 870"
filesystem:
  type: xfs
  projectQuotaSupport: true
