---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crunchy-postgres-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        POSTGRESQL_R2_ENDPOINT: "{{ .POSTGRESQL_R2_ENDPOINT }}"
  data:
    - secretKey: POSTGRESQL_R2_ENDPOINT
      remoteRef:
        key: 3e72a2e9-c430-4e86-b9d8-242601989b58
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-pguser-postgres
  labels:
    postgres-operator.crunchydata.com/cluster: postgres
    postgres-operator.crunchydata.com/pguser: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    creationPolicy: Orphan
  data:
    - secretKey: password
      remoteRef:
        key: 7f745351-28d9-4d05-b838-92dc3a92eb01
