---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-operator
spec:
  interval: 1h
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  path: ./kubernetes/apps/database/emqx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-cluster
spec:
  interval: 1h
  dependsOn:
    - name: emqx-operator
    - name: external-secrets-stores
      namespace: external-secrets
    - name: prometheus-operator-crds
      namespace: observability
  path: ./kubernetes/apps/database/emqx/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  healthCheckExprs:
    - apiVersion: apps.emqx.io/v2beta1
      kind: EMQX
      current: status.conditions.exists(condition, condition.type == "Available" && condition.status == "True")
      failed: status.conditions.exists(condition, condition.type == "Available" && condition.status == "False")
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-exporter
spec:
  interval: 1h
  dependsOn:
    - name: emqx-cluster
    - name: external-secrets-stores
      namespace: external-secrets
    - name: prometheus-operator-crds
      namespace: observability
  path: ./kubernetes/apps/database/emqx/exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
