---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miscale2pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres
  target:
    template:
      data:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-rw.database.svc.cluster.local:5432/{{ .username }}"
        SPRING_DATASOURCE_USERNAME: "{{ .username }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-miscale2pg
