---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
resources:
  requests:
    cpu: 200m
    memory: 2Gi
  limits:
    memory: 2Gi
---
apiVersion: v1alpha1
kind: KubeAdmissionControlConfig
name: PodSecurity
$patch: delete
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    conditions:
      - path: /livez
      - path: /readyz
      - path: /healthz
    enabled: true
  jwt: []
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeletConfig
config:
  imageMaximumGCAge: 168h
  maxParallelImagePulls: 3
  serializeImagePulls: false
  shutdownGracePeriod: 90s
  shutdownGracePeriodCriticalPods: 60s
---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - system-upgrade
