---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: snapshot-controller
  values:
    controller:
      serviceMonitor:
        create: true
