---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      zigbee2mqtt:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: feature.node.kubernetes.io/usb-ff_10c4_ea60.present
                        operator: In
                        values: ["true"]
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.5.1
            env:
              TZ: "Europe/Sofia"
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx-listeners.database.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyACM0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee.nasenov.dev
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: zigbee2mqtt
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              privileged: true

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - zigbee2mqtt.nasenov.dev
          - zigbee.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: zigbee2mqtt
        globalMounts:
          - path: /app/data
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_cc6b105fee12ec11945f20c7bd930c07-if00-port0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/ttyACM0
