---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap Kubernetes cluster
    cmds:
      - task: terraform-apply
        vars:
          TERRAFORM_DIRECTORY: "{{.ROOT_DIR}}/terraform/kubernetes"
      - task: terraform-apply
        vars:
          TERRAFORM_DIRECTORY: "{{.ROOT_DIR}}/terraform/bootstrap"

  destroy:
    desc: Destroy Kubernetes cluster
    dir: "{{.ROOT_DIR}}/terraform/kubernetes"
    cmd: terraform destroy
    preconditions:
      - which terraform

  terraform-apply:
    internal: true
    dir: "{{.TERRAFORM_DIRECTORY}}"
    cmds:
      - terraform init
      - terraform apply
    preconditions:
      - which terraform
