---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap Kubernetes cluster
    cmds:
      - task: terraform-apply
        vars:
          TERRAFORM_DIRECTORY: "{{.ROOT_DIR}}/terraform/kubernetes"
      - task: terraform-apply
        vars:
          TERRAFORM_DIRECTORY: "{{.ROOT_DIR}}/terraform/bootstrap"

  reset-talos-upgrade:
    desc: Reset failed Talos upgrade
    cmd: kubectl --namespace system-upgrade annotate talosupgrade talos tuppr.home-operations.com/reset="$(date)"
    preconditions:
      - which kubectl

  destroy:
    desc: Destroy Kubernetes cluster
    dir: "{{.ROOT_DIR}}/terraform/kubernetes"
    cmds:
      - talosctl reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --system-labels-to-wipe u-openebs --graceful=false --reboot
      - terraform state rm $(terraform state list)
    preconditions:
      - which talosctl
      - which terraform

  terraform-apply:
    internal: true
    dir: "{{.TERRAFORM_DIRECTORY}}"
    cmds:
      - terraform init
      - terraform apply
    preconditions:
      - which terraform
