---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        pod:
          restartPolicy: Never
        initContainers:
          tag: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.21.1@sha256:fd13085f7534719b7b30828684661b7f5611bbc4156831123775cfcd9b8f2eb5
            args:
              - "tagging"
              - "--added-on"
              - "--expired"
              - "--last-activity"
              - "--sites"
              - "--unregistered"
            env:
              QBITTORRENT_HOST: qbittorrent.default.svc.cluster.local
              QBITTORRENT_PORT: 80
            envFrom:
              - secretRef:
                  name: qbtools
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          unregistered:
            <<: *container
            args:
              - "prune"
              - "--exclude-category"
              - "manual"
              - "--exclude-tag"
              - "added:1d"
              - "--include-tag"
              - "unregistered"
              - "--with-data"
              # - "--dry-run"
          expired:
            <<: *container
            args:
              - "prune"
              - "--include-category"
              - "autobrr"
              - "--include-category"
              - "cross-seed"
              - "--include-tag"
              - "expired"
              - "--with-data"
              # - "--dry-run"

      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: 0 0 * * 0
        pod:
          restartPolicy: Never
        containers:
          app:
            <<: *container
            args:
              - "orphaned"
              - "--exclude-pattern"
              - "*_unpackerred*"
              - "--exclude-pattern"
              - "*/manual/*"
              # - "--dry-run"

      reannounce:
        containers:
          app:
            <<: *container
            args: ["reannounce", "--process-seeding"]

    persistence:
      secret-file:
        type: secret
        name: qbtools-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        enabled: true
        type: nfs
        server: 192.168.0.15
        path: /mnt/tank/media
        advancedMounts:
          orphaned:
            app:
              - path: /data/downloads
                subPath: downloads
