---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        token: "{{ .FLUX_GITHUB_TOKEN }}"
  data:
    - secretKey: FLUX_GITHUB_TOKEN
      remoteRef:
        key: 3d30d69d-beef-444c-8fc2-c42787511c08
