---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tqm
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tqm
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      tqm:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: "@hourly"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          retag: &container
            image:
              repository: ghcr.io/home-operations/tqm
              tag: 1.17.0@sha256:05b62239063ad1e884f2254532e3dc9b60cff08870112dca244af328d761be0d
            args:
              - retag
              - qb
              # - --dry-run
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          clean:
            <<: *container
            args:
              - clean
              - qb
              # - --dry-run

        pod:
          restartPolicy: Never
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@weekly"
        containers:
          app:
            <<: *container
            args:
              - orphan
              - qb
              - --dry-run
        pod:
          restartPolicy: Never

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /.config/tqm
      secret-file:
        type: secret
        name: "{{ .Release.Name }}"
        globalMounts:
          - path: /.config/tqm/config.yaml
            subPath: config.yaml
      media:
        type: nfs
        server: truenas.nasenov.dev
        path: /mnt/tank/media
        globalMounts:
          - path: /data/downloads
            subPath: downloads
            readOnly: true
