---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
