---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  init:
    desc: Initialize Terraform directories
    cmds:
      - for: {var: TF_DIRS, split: "\n"}
        cmd: terraform -chdir={{.ITEM}} init -upgrade
    vars:
      TF_DIRS:
        sh: find {{.ROOT_DIR}}/terraform -mindepth 1 -maxdepth 1 -type d
    preconditions:
      - which terraform

  sync-tfvars:
    desc: Sync terraform tfvars
    cmds:
      - bws secret get 3218d99d-71fa-4c83-9e61-74978941d19f | jq --raw-output '.value' > {{.ROOT_DIR}}/terraform/cloudflare/terraform.tfvars
    preconditions:
      - which bws
      - which jq

  apply:
    desc: Apply Terraform configuration
    requires:
      vars:
        - TF_DIR
    cmd: terraform -chdir={{.TF_DIR}} apply
    preconditions:
      - which terraform

  output:
    desc: Read Terraform output variable
    requires:
      vars:
        - TF_DIR
        - TF_OUTPUT
    cmd: terraform -chdir={{.TF_DIR}} output --raw {{.TF_OUTPUT}}
    preconditions:
      - which terraform

  purge:
    desc: Purge Terraform state
    requires:
      vars:
        - TF_DIR
    cmd: terraform -chdir={{.TF_DIR}} state rm $(terraform -chdir={{.TF_DIR}} state list)
    preconditions:
      - which terraform
