---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: cssurf
    files:
      - csserver.cfg=./resources/csserver.cfg
      - lgsm.cfg=./resources/lgsm.cfg
      - mapcycle.txt=./resources/mapcycle.txt
generatorOptions:
  disableNameSuffixHash: true
