---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tqm
spec:
  targetNamespace: default
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: qbittorrent
      namespace: default
  path: ./kubernetes/apps/default/tqm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
