---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bazarr
spec:
  interval: 1h
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/default/bazarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: bazarr
