---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: nasenov-dev-tls
spec:
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden-secrets-manager
  selector:
    secret:
      name: nasenov-dev-tls
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: NASENOV_DEV_TLS_CRT
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: NASENOV_DEV_TLS_KEY
