---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cskz
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cskz
  values:
    controllers:
      cskz:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          config:
            enabled: false
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
            command:
              - sh
              - -c
              - |
                cp /config/mapcycle.txt /data/serverfiles/cstrike/mapcycle.txt
                rm -f /data/serverfiles/cstrike/addons/amxmodx/configs/maps.ini
                cp /config/csserver.cfg /data/serverfiles/cstrike/csserver.cfg
                cp /secret/secrets.cfg /data/serverfiles/cstrike/secrets.cfg
                cp /config/lgsm.cfg /data/config-lgsm/csserver/common.cfg
        containers:
          app:
            image:
              repository: ghcr.io/gameservermanagers/gameserver
              tag: cs@sha256:a6ce816c2ae7cf4a396fbc82f48d6461d9884f871e77dbf3261ad16825232bae
            env:
              LGSM_GITHUBUSER: nasenov
              LGSM_GITHUBREPO: LinuxGSM
              LGSM_GITHUBBRANCH: fix/bump-amxmodx-version
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 256Mi

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.46
        ports:
          game:
            port: 27017
            protocol: UDP

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 4Gi
      config:
        type: configMap
        name: "{{ .Release.Name }}"
      secret:
        type: secret
        name: "{{ .Release.Name }}"
