---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-exporter
spec:
  targetNamespace: observability
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  components:
    - ../../../../components/defaults
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
  path: ./kubernetes/apps/observability/node-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
