---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  path: ./kubernetes/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
  patches:
    - # Add Sops decryption to child Kustomizations
      patch: |-
        - op: add
          path: /spec/decryption
          value:
            provider: sops
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
