---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  targetNamespace: observability
  dependsOn:
    - name: prometheus-operator-crds
  path: ./kubernetes/apps/observability/kube-state-metrics/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
