---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-endpoint
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        R2_ENDPOINT_URL: "{{ .POSTGRESQL_R2_ENDPOINT }}"
  data:
    - secretKey: POSTGRESQL_R2_ENDPOINT
      remoteRef:
        key: 3e72a2e9-c430-4e86-b9d8-242601989b58
