---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  uid: 345941b8-786a-4924-9465-3f109c8361b4
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: prometheus
    name: prometheus
    access: proxy
    isDefault: true
    url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  uid: eb649bce-93a2-4dbe-b558-e7739ed5903e
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: alertmanager
    name: alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: infinity
spec:
  uid: c21ac472-da08-4012-ae55-7b428c6caa21
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: yesoreyeram-infinity-datasource
    name: infinity
    access: proxy
  plugins:
    - name: yesoreyeram-infinity-datasource
      version: latest
