---
services:
  garage:
    container_name: garage
    image: dxflrs/garage:v2.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.s3.rule=Host(`s3.truenas.nasenov.dev`)
      - traefik.http.routers.s3.service=s3
      - traefik.http.services.s3.loadbalancer.server.port=3900
      - traefik.http.routers.garage.rule=Host(`garage.truenas.nasenov.dev`)
      - traefik.http.routers.garage.service=garage
      - traefik.http.services.garage.loadbalancer.server.port=3903
    restart: unless-stopped
    environment:
      GARAGE_ALLOW_WORLD_READABLE_SECRETS: "true"
      GARAGE_RPC_SECRET_FILE: /run/secrets/garage_rpc_secret
      GARAGE_ADMIN_TOKEN_FILE: /run/secrets/garage_admin_token
    secrets:
      - garage_rpc_secret
      - garage_admin_token
    networks:
      apps_bridge:
    volumes:
      - /mnt/tank/apps/garage/garage.toml:/etc/garage.toml
      - /mnt/tank/apps/garage/meta:/var/lib/garage/meta
      - /mnt/tank/apps/garage/data:/var/lib/garage/data

secrets:
  garage_rpc_secret:
    file: /mnt/tank/apps/garage/garage_rpc_secret
  garage_admin_token:
    file: /mnt/tank/apps/garage/garage_admin_token

networks:
  apps_bridge:
    external: true
