---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync-terraform-tfvars:
    desc: Sync terraform tfvars
    silent: true
    cmds:
      - bws secret get 95ae7587-8b74-4663-89ae-b42e00eb0a67 | jq --raw-output '.value' > {{.ROOT_DIR}}/terraform/cloudflare/terraform.tfvars
    preconditions:
      - which bws
      - which jq
