---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync-terraform-tfvars:
    desc: Sync terraform tfvars
    silent: true
    cmds:
      - bws secret get 3218d99d-71fa-4c83-9e61-74978941d19f | jq --raw-output '.value' > {{.ROOT_DIR}}/terraform/cloudflare/terraform.tfvars
    preconditions:
      - which bws
      - which jq
