---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync-terraform-tfvars:
    desc: Sync terraform tfvars
    silent: true
    cmds:
      - bw get notes bootstrap.tfvars > {{.ROOT_DIR}}/terraform/bootstrap/terraform.tfvars
      - bw get notes cloudflare.tfvars > {{.ROOT_DIR}}/terraform/cloudflare/terraform.tfvars
      - bw get notes kubernetes.tfvars > {{.ROOT_DIR}}/terraform/kubernetes/terraform.tfvars
      - bw get notes proxmox.tfvars > {{.ROOT_DIR}}/terraform/proxmox/terraform.tfvars
    preconditions:
      - which bw
      - bw login --check
      - bw unlock --check
