---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync-all-secrets:
    cmds:
      - task: sync-agekey
      - task: sync-terraform-tfvars

  sync-agekey:
    desc: Sync agekey
    silent: true
    cmd: bw get notes agekey > {{.ROOT_DIR}}/age.agekey
    preconditions:
      - which bw
      - bw login --check
      - bw unlock --check

  sync-terraform-tfvars:
    desc: Sync terraform tfvars
    silent: true
    cmds:
      - bw get notes cloudflare.tfvars > {{.ROOT_DIR}}/terraform/cloudflare/terraform.tfvars
      - bw get notes kubernetes.tfvars > {{.ROOT_DIR}}/terraform/kubernetes/terraform.tfvars
      - bw get notes proxmox.tfvars > {{.ROOT_DIR}}/terraform/proxmox/terraform.tfvars
    preconditions:
      - which bw
      - bw login --check
      - bw unlock --check
