---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miscale2pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres
  target:
    template:
      data:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .pgbouncer_host }}:{{ .pgbouncer_port }}/{{ .dbname }}"
        SPRING_DATASOURCE_USERNAME: "{{ .user }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-miscale2pg
      rewrite:
        - regexp:
            source: "-"
            target: "_"
