---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miscale2pg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: miscale2pg
  values:
    controllers:
      miscale2pg:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/nasenov/miscale2pg
              tag: 0.0.6@sha256:58df1ff4d772dccdfb02dda66ac8b7a2ecdd81197b7210ec9805546392555753
            env:
              SERVER_PORT: &port 80
              BPL_JVM_THREAD_COUNT: 50
              JAVA_TOOL_OPTIONS: -Xss512k -XX:ReservedCodeCacheSize=48M
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /actuator/health/liveness
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /actuator/health/readiness
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        endpoints:
          - port: http
            path: /actuator/prometheus

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nasenov.dev"
        parentRefs:
          - name: envoy-internal
            namespace: networking

    persistence:
      tmp:
        type: emptyDir
