---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cstrike
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cstrike
  values:
    controllers:
      cstrike:
        containers:
          app:
            image:
              repository: ghcr.io/gameservermanagers/gameserver
              tag: cs@sha256:2ea3d841b2bb4a91d2be878848ab84feafa6bd2f9400ae3ff098e4dc63c4f435
            env:
              LGSM_GITHUBBRANCH: develop
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        ports:
          game:
            port: 27015
            protocol: UDP

    route:
      app:
        kind: UDPRoute
        parentRefs:
          - name: envoy-external
            namespace: networking

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
