---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  terraform:
    taskfile: ../terraform
    internal: true

vars:
  KUBERNETES_BOOTSTRAP_DIR: "{{.ROOT_DIR}}/kubernetes/bootstrap/helmfile"
  TALOS_BOOTSTRAP_DIR: "{{.ROOT_DIR}}/terraform/talos"

tasks:
  bootstrap:
    desc: Bootstrap Kubernetes cluster
    cmds:
      - task: terraform:apply
        vars:
          TF_DIR: "{{.TALOS_BOOTSTRAP_DIR}}"
      - task: fetch-talosconfig
      - task: fetch-kubeconfig
      - task: kubernetes-apply-resources
      - task: helmfile

  fetch-talosconfig:
    desc: Fetch the talosconfig
    dir: "{{.ROOT_DIR}}"
    cmd: sh -c 'umask 077 && task terraform:output TF_DIR={{.TALOS_BOOTSTRAP_DIR}} TF_OUTPUT=talosconfig > talosconfig'

  fetch-kubeconfig:
    desc: Fetch the admin kubeconfig
    cmd: talosctl kubeconfig  --nodes {{.CONTROLLER}} --force {{.ROOT_DIR}}
    vars:
      CONTROLLER:
        sh: talosctl config info -o json | jq '.endpoints.[0]'
    preconditions:
      - which talosctl
      - which jq

  reset-talos-upgrade:
    desc: Reset failed Talos upgrade
    cmd: kubectl --namespace system-upgrade annotate talosupgrade talos tuppr.home-operations.com/reset="$(date)"
    preconditions:
      - which kubectl

  destroy:
    desc: Destroy Kubernetes cluster
    cmds:
      - talosctl reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --system-labels-to-wipe u-openebs --graceful=false --reboot
      - task: terraform:purge
        vars:
          TF_DIR: "{{.TALOS_BOOTSTRAP_DIR}}"
    preconditions:
      - which talosctl

  kubernetes-apply-resources:
    internal: true
    cmds:
      - kubectl create namespace external-secrets --dry-run=client -o yaml | kubectl apply -f -
      - |-
        kubectl create secret generic bitwarden-access-token --namespace external-secrets \
        --from-literal=token="$(bws secret get baf8e9bc-d0a7-447a-93c7-7d93b4d20597 | jq --raw-output '.value')" \
        --dry-run=client -o yaml | kubectl apply -f -
    preconditions:
      - which kubectl
      - which bws
      - which jq

  helmfile:
    internal: true
    cmds:
      - helmfile --file {{.KUBERNETES_BOOTSTRAP_DIR}}/crds.yaml template --quiet | yq ea -e 'select(.kind == "CustomResourceDefinition")' | kubectl apply --server-side -f -
      - helmfile --file {{.KUBERNETES_BOOTSTRAP_DIR}}/apps.yaml sync --hide-notes
    preconditions:
      - test -f {{.KUBERNETES_BOOTSTRAP_DIR}}/crds.yaml
      - test -f {{.KUBERNETES_BOOTSTRAP_DIR}}/apps.yaml
      - which helmfile
      - which kubectl
      - which yq
