---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap Kubernetes cluster
    cmds:
      - task: terraform-apply
        vars:
          TERRAFORM_DIRECTORY: "{{.ROOT_DIR}}/terraform/talos"
      - task: fetch-talosconfig
      - task: fetch-kubeconfig
      - task: kubernetes-apply-resources
      - task: helmfile

  fetch-talosconfig:
    desc: Fetch the talosconfig
    dir: "{{.ROOT_DIR}}/terraform/talos"
    cmd: sh -c 'umask 077 && terraform output --raw talosconfig > {{.ROOT_DIR}}/talosconfig'
    preconditions:
      - which terraform

  fetch-kubeconfig:
    desc: Fetch the admin kubeconfig
    cmd: talosctl kubeconfig  --nodes {{.CONTROLLER}} --force {{.ROOT_DIR}}
    vars:
      CONTROLLER:
        sh: talosctl config info -o json | jq '.endpoints.[0]'
    preconditions:
      - which talosctl
      - which jq

  reset-talos-upgrade:
    desc: Reset failed Talos upgrade
    cmd: kubectl --namespace system-upgrade annotate talosupgrade talos tuppr.home-operations.com/reset="$(date)"
    preconditions:
      - which kubectl

  destroy:
    desc: Destroy Kubernetes cluster
    dir: "{{.ROOT_DIR}}/terraform/talos"
    cmds:
      - talosctl reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --system-labels-to-wipe u-openebs --graceful=false --reboot
      - terraform state rm $(terraform state list)
    preconditions:
      - which talosctl
      - which terraform

  terraform-apply:
    internal: true
    dir: "{{.TERRAFORM_DIRECTORY}}"
    cmds:
      - terraform init
      - terraform apply
    preconditions:
      - which terraform

  kubernetes-apply-resources:
    internal: true
    cmds:
      - kubectl create namespace external-secrets --dry-run=client -o yaml | kubectl apply -f -
      - |-
        kubectl create secret generic bitwarden-access-token --namespace external-secrets \
        --from-literal=token="$(bws secret get 4fef3a89-a129-48cf-8754-b3cb014a6ca1 | jq --raw-output '.value')" \
        --dry-run=client -o yaml | kubectl apply -f -
    preconditions:
      - which kubectl
      - which bws
      - which jq

  helmfile:
    internal: true
    cmds:
      - helmfile --file {{.ROOT_DIR}}/bootstrap/crds.yaml template --quiet | yq ea -e 'select(.kind == "CustomResourceDefinition")' | kubectl apply -f -
      - helmfile --file {{.ROOT_DIR}}/bootstrap/helmfile.d/apps.yaml sync --hide-notes
    preconditions:
      - test -f {{.ROOT_DIR}}/bootstrap/crds.yaml
      - test -f {{.ROOT_DIR}}/bootstrap/apps.yaml
      - which helmfile
      - which kubectl
      - which yq
