---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  interval: 1h
  chart:
    spec:
      chart: ceph-csi-drivers
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-drivers
  values:
    operatorConfig:
      namespace: rook-ceph
      driverSpecDefaults:
        clusterName: rook-ceph
        imageSet:
          name: rook-csi-operator-image-set-configmap
        snapshotPolicy: volumeSnapshot
        nodePlugin:
          priorityClassName: system-node-critical
          resources:
            plugin:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            registrar:
              requests:
                cpu: 50m
                memory: 16Mi
              limits:
                memory: 16Mi
        controllerPlugin:
          replicas: 2
          deploymentStrategy:
            type: Recreate
          priorityClassName: system-cluster-critical
          resources:
            attacher:
              requests:
                cpu: 100m
                memory: 32Mi
              limits:
                memory: 32Mi
            plugin:
              requests:
                memory: 128Mi
              limits:
                memory: 256Mi
            provisioner:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                memory: 64Mi
            resizer:
              requests:
                cpu: 100m
                memory: 32Mi
              limits:
                memory: 32Mi
            snapshotter:
              requests:
                cpu: 100m
                memory: 32Mi
              limits:
                memory: 32Mi

    drivers:
      rbd:
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
        kernelMountOptions: ms_mode=prefer-crc
        controllerPlugin:
          replicas: 2
          deploymentStrategy:
            type: Recreate

      nvmeof:
        enabled: false

      cephfs:
        enabled: false

      nfs:
        enabled: false
