---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./alloy/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./kromgo/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./loki/ks.yaml
  - ./node-exporter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./smartctl-exporter/ks.yaml
