---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
spec:
  targetNamespace: observability
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: openebs
      namespace: openebs
  path: ./kubernetes/apps/observability/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
