---
services:
  smartctl-exporter:
    container_name: smartctl-exporter
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      apps_bridge:

networks:
  apps_bridge:
    external: true
