---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
  data:
    - secretKey: QUI_SESSION_SECRET
      remoteRef:
        key: 91d2776a-a288-48b4-8ef2-5df7730b260d
