---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
spec:
  targetNamespace: storage
  interval: 30m
  retryInterval: 2m
  timeout: 5m
  dependsOn:
    - name: snapshot-controller
      namespace: storage
    - name: prometheus-operator-crds
      namespace: observability
  path: ./kubernetes/apps/storage/volsync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
