---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: emqx-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      emqx-exporter:
        replicas: 1
        strategy: RollingUpdate
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/emqx/emqx-exporter
              tag: 0.2.11@sha256:31173023132078a9243527ff1dbaae5facc77b8d3708a3b018634f8ba8862ec9
            args:
              - --config.file
              - /etc/emqx-exporter/config.yaml
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          metrics:
            port: 8085

    serviceMonitor:
      app:
        endpoints:
          - port: metrics
            path: /metrics
            relabelings:
              - action: replace
                # user-defined cluster name, requires unique
                replacement: emqx
                targetLabel: cluster
              - action: replace
                # fix value, don't modify
                replacement: exporter
                targetLabel: from
              - action: replace
                # fix value, don't modify
                sourceLabels: ["pod"]
                regex: "(.*)-.*-.*"
                replacement: $1
                targetLabel: "instance"
              - action: labeldrop
                # fix value, don't modify
                regex: "pod"
          - port: metrics
            path: /probe
            params:
              target:
                - "emqx-listeners.database.svc.cluster.local:1883"
            relabelings:
              - action: replace
                # user-defined cluster name, requires unique
                replacement: emqx
                targetLabel: cluster
              - action: replace
                # fix value, don't modify
                replacement: exporter
                targetLabel: from
              - action: replace
                # fix value, don't modify
                sourceLabels: ["pod"]
                regex: "(.*)-.*-.*"
                replacement: $1
                targetLabel: "instance"
              - action: labeldrop
                # fix value, don't modify
                regex: "pod"

    persistence:
      config:
        type: secret
        name: "{{ .Release.Name }}"
        globalMounts:
          - path: /etc/emqx-exporter
