---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: timetagger
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      timetagger:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/almarklein/timetagger
              tag: v25.06.1-nonroot@sha256:32529ffb8e9b4b5c0f2caad71476d0a02eece8e0355963d3649f6789cfd2a4f2
            env:
              TIMETAGGER_BIND: 0.0.0.0:80
              TIMETAGGER_DATADIR: /opt/_timetagger
            envFrom:
              - secretRef:
                  name: timetagger
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 80

    route:
      app:
        hostnames:
          - timetagger.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: timetagger
        globalMounts:
          - path: /opt/_timetagger
