---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: b6337031-d084-4537-9da9-b4da01092ff3
