---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .POSTGRESQL_POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRESQL_POSTGRES_PASSWORD
      remoteRef:
        key: 7f745351-28d9-4d05-b838-92dc3a92eb01
