---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seasonpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        SEASONPACKARR__CLIENTS_DEFAULT_USERNAME: "{{ .QBITTORRENT_ADMIN_USERNAME }}"
        SEASONPACKARR__CLIENTS_DEFAULT_PASSWORD: "{{ .QBITTORRENT_ADMIN_PASSWORD }}"
  data:
    - secretKey: QBITTORRENT_ADMIN_USERNAME
      remoteRef:
        key: 808dd29b-3224-463d-8c7c-b41c0123402e
    - secretKey: QBITTORRENT_ADMIN_PASSWORD
      remoteRef:
        key: fcf409e5-b07d-4079-b2e9-b41c012353aa
