---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cs
  values:
    controllers:
      cs:
        containers:
          app:
            image:
              repository: ghcr.io/gameservermanagers/gameserver
              tag: cs@sha256:a6ce816c2ae7cf4a396fbc82f48d6461d9884f871e77dbf3261ad16825232bae
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 256Mi

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.44
        ports:
          game:
            port: 27015
            protocol: UDP

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 16Gi
