---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cs
  values:
    controllers:
      cs:
        containers:
          app:
            image:
              repository: ghcr.io/gameservermanagers/gameserver
              tag: cs@sha256:6e7abdc2be44c26002807f16d7a1948624e2a0996cea2f3a8177caf494a5c043
            resources:
              requests:
                cpu: 500m
              limits:
                memory: 512Mi

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.0.44
        ports:
          game:
            port: 27015
            protocol: UDP

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 16Gi
