---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cs
spec:
  sourcePVC: cs
  trigger:
    schedule: 0 * * * *
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: cs-volsync-local
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 1Gi
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
