apiVersion: v1
kind: Secret
metadata:
  name: github-token
stringData:
  token: ENC[AES256_GCM,data:XQu8KjAfwv2DfLyFuKxRitfmi08S5dePnGIxpXLfW//ZVdksGt1JQw==,iv:wil1Ip2N6qQTLQ4kqHFISNyC/uZ1c0xOIZA++AcCwEI=,tag:gS1GzrFkmkXyMOv9ZASF3w==,type:str]
sops:
  age:
    - recipient: age128pzspekap6pjzu53vzfn9t6xpvazq0z6qxxj79v27mke4urup9qqqhq4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dm0rcTFmYUtjaW1CREN1
        R2JxOTBrb1RrK1hoajYxbUl6bGZsbndrVVN3CnVjMi9UN0RCR2h6V0Z0dUJnRXhX
        Q0J3YkJETE9vMzgxNVBPdHQ1Z01adVEKLS0tIGxMN0E0OGozMDZjQm1BZi9GQ2tC
        VmlLSWViVmFrRTEyUGlDM2U2V0dvSXMKt1VZAsYYLAQfqV4TutakeRaBUmEK9IrO
        PYui1mmv9S9tzZ6cPmyLVBAvxaCWS8OkmYin8S2akEIt5kp3Lnr3IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T07:04:44Z"
  mac: ENC[AES256_GCM,data:X1lS9MPz1Pa7LsTaFAUtoOMrdbpe4UC20luJP7RhDwHdaEUc8TaaEsO6ifxasCbJlYoeDI1ogbalmPmu4T05H/B4p56li2Zw6ymhh/TfDn2KQFrLI/GUJQGRJsgZ9UeIVhP33OHUTGpIE7bRkIUpSZQSRaoST0odQeFW7mwaZN0=,iv:1ForxoLUjhoQG1OaPZMJEOpvrZ9ujSriIf88DvhzLPU=,tag:wu+z4M+/7oFXWsAxmBUudw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
