---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  values:
    image:
      repository: ghcr.io/rook/ceph

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi

    ceph-csi-operator:
      controllerManager:
        manager:
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: null
              memory: 128Mi

    monitoring:
      enabled: true
