---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  values:
    image:
      repository: ghcr.io/rook/ceph

    csi:
      serviceMonitor:
        enabled: true
        interval: 30s

    monitoring:
      enabled: true
