apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:pcTYVeZAGmt3nwWwaR60pKqeV/PmvKBu7cxWva9kS2FmI55m8S1EjyOmJbgOAFUP91nk0KO3rEvrHQM+KeimfDnzHFDZ4zyVB8lhXCn0Re/dhJ0q+YbwjCVu60iL/lzGh0Rck2te/owcxCzsqkPJex68Qce8KxLBhAWw+Gqsvyr5SxqzjAJikpdmXeYJ2VLp+vj2U8pWc+mkxOnbiy4L98qMT2M9litEI2oHFtv0yrpHk5JTCc7RDJ0xJMk9,iv:CT7ejXJ9k6PMuYAwvLU30mBAYPTNxxWDyCbT0WOi9cY=,tag:klQb2qqD8jhrxTpYSMFPDA==,type:str]
sops:
  age:
    - recipient: age128pzspekap6pjzu53vzfn9t6xpvazq0z6qxxj79v27mke4urup9qqqhq4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL3AvbEVwVmpuQlhkOHFk
        WE1FZUgzNmltSUpYZ2oxSDd6K25TbisxOVQ4CjVYdDJNaXRZdHpNU2JITk1CUjB3
        ak9JR0JsWmhZMDR0cG5mTE92KzhDVVkKLS0tIGdCM3B5anFDbmdBVmJsaEgrNEVB
        YSs5aHhWMGJmbldJaVVOWElHWFMwK1EK0q5eI9ZtzSLp+5+EbjF+ubA5AmSj23Li
        pe3h9j+G9MkWDL4hPygwzWegTh/NOZcezQtDMBFFvW95hlCq4LjvHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T07:04:18Z"
  mac: ENC[AES256_GCM,data:o1vgttJmqBCg3b3qfR5kxBBXO9jzF58N1hZUS8wsnHYVTfdoVavH7oaljNM1TDZtbi14DpO9TDz9EDMkCPnPrcvG4lTF6T+KSRmerIA70TXLsPI3KyyQ5ZQREB+XDpJ9PqCzjL8G+57kksEgIW9Pe6hExRu1gVTSqcwUvcLRQzQ=,iv:k9cEjasVBCk2yumbEXZlKBUOzk49QekIv8win//Up1E=,tag:lWMbQNpYaQnrDWLoZKfPEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
