---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-pihole
spec:
  interval: 1h
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/networking/external-dns-pihole/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-pihole-dnsendpoint
spec:
  interval: 1h
  dependsOn:
    - name: external-dns-pihole
  path: ./kubernetes/apps/networking/external-dns-pihole/dnsendpoint
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
