---
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/ylianst/meshcentral:1.1.57
    restart: unless-stopped
    networks:
      apps_bridge:
    volumes:
      - /mnt/apps/meshcentral/data:/opt/meshcentral/meshcentral-data
      - /mnt/apps/meshcentral/files:/opt/meshcentral/meshcentral-files

networks:
  apps_bridge:
    external: true
