---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      calibre-web-automated:
        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: V3.1.4@sha256:577e846f104fd21453ef306eefb4a95dd95b3b9ddd2463a150944494284da0fd
            env:
              TZ: Europe/Sofia
              PUID: 1000
              PGID: 1000
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: 8083

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nasenov.dev"
          - cwa.nasenov.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: truenas.nasenov.dev
        path: /mnt/tank/media
        globalMounts:
          - path: /cwa-book-ingest
            subPath: media/cwa/cwa-book-ingest
          - path: /calibre-library
            subPath: media/cwa/calibre-library
      tmpfs:
        type: emptyDir
        advancedMounts:
          calibre-web-automated:
            app:
              - path: /cache
                subPath: cache
